#!/usr/bin/env bash
# Write a Bash script that loops from 1 to 10 and

number=1
while [[ $number -ne 10 ]]
do
	if [ "$number" == '4' ]; then
	echo "bad luck"
	elif [ "$number" == '8' ]; then
	echo "good luck"
	else	echo "Best School"
	fi
	((number++))
done
