#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"; rm -rf /var/run/myscript.pid; exit' SIGINT
echo "$$" >> /var/run/holbertonscript.pid                        
while ((2))
do                                                                                                                    
	echo "To infinity and beyond"
	sleep 2
done
