#!/usr/bin/env bash
# This script creates the file /var/run/holbertonscript.pid containing its PID
trap "echo I hate the kill command;love" SIGTERM
trap "echo Y U no love me?!;love" SIGINT
echo $$ >> /var/run/holbertonscript.pid                                                                                               
while ((2));
do                                                                                                                    
	echo "To infinity and beyond"
	sleep 2
done
